---
kind: pipeline
type: kubernetes
name: linter

platform:
  os: linux
  arch: amd64

steps:
- name: markdown lint
  commands:
  - markdownlint *.md
  image: docker.io/tmknom/markdownlint:0.23.1
  resources:
    limits:
      cpu: 50
      memory: 50M

- name: email-notification
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 50
      memory: 25M
  when:
    status:
    - changed
    - failure

trigger:
  event:
    exclude:
    - tag
---
kind: pipeline
type: docker
name: build-latest

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/build
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master

- name: push
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/push
  environment:
    POSTFIXADMIN_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master
    repo:
    - volker.raschek/postfixadmin-docker

- name: delete
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/delete
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    branch:
    - master

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - tag

---
kind: pipeline
type: docker
name: build-tagged

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/build POSTFIXADMIN_IMAGE_VERSION=${DRONE_TAG}
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: push
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/push POSTFIXADMIN_IMAGE_VERSION=${DRONE_TAG}
  environment:
    POSTFIXADMIN_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: delete
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make container-image/delete POSTFIXADMIN_IMAGE_VERSION=${DRONE_TAG}
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - tag
  repo:
  - volker.raschek/postfixadmin-docker
---
kind: pipeline
type: kubernetes
name: sync

platform:
  os: linux
  arch: amd64

steps:
- name: github
  image: docker.io/appleboy/drone-git-push:latest
  resources:
    limits:
      cpu: 50
      memory: 25M
  settings:
    branch: master
    remote: ssh://git@github.com/volker-raschek/postfixadmin-docker.git
    force: true
    ssh_key:
      from_secret: ssh_key

- name: email-notification
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 50
      memory: 25M
  when:
    status:
    - changed
    - failure

trigger:
  event:
  - push
  repo:
  - volker.raschek/postfixadmin-docker
